"""Web Bridge records, enums, and state transition rules."""

from .enums import (
    AuditKind,
    BatchState,
    BatchTargetState,
    CommandSource,
    CommandState,
    DeviceLifecycle,
    LeaseState,
    SessionState,
    TERMINAL_COMMAND_STATES,
    MaintenanceTaskState,
    RolloutTaskState,
)
from .records import (
    AuditRecord,
    BatchTarget,
    BatchTask,
    CommandRecord,
    DeviceRecord,
    DeviceSession,
    DiscoveryCandidate,
    ControlLease,
    MaintenanceTask,
    RolloutTask,
    utc_now,
)
from .transitions import transition_batch, transition_command, transition_lease, transition_session, transition_maintenance, transition_rollout

__all__ = [
    "AuditKind",
    "AuditRecord",
    "BatchState",
    "BatchTarget",
    "BatchTargetState",
    "BatchTask",
    "CommandRecord",
    "CommandSource",
    "CommandState",
    "DeviceLifecycle",
    "DeviceRecord",
    "DeviceSession",
    "ControlLease",
    "DiscoveryCandidate",
    "SessionState",
    "LeaseState",
    "TERMINAL_COMMAND_STATES",
    "transition_command",
    "transition_batch",
    "transition_lease",
    "transition_session",
    "transition_maintenance",
    "transition_rollout",
    "utc_now",
    "MaintenanceTask",
    "RolloutTask",
    "MaintenanceTaskState",
    "RolloutTaskState",
]
