"""Generate and exercise the small Codex app-server protocol contract.

The checked-in schemas are generated by the locally installed ``codex`` CLI.
The offline contract runner deliberately never starts an app-server process and
never sends a request, so it is safe to run without credentials.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_DIR = ROOT / "contracts" / "codex"
SCHEMA_FILES = ("ClientRequest.json", "JSONRPCRequest.json")
MANIFEST_FILE = "manifest.json"
REQUIRED_METHODS = ("initialize", "thread/start", "turn/start", "turn/interrupt")


def _codex() -> str:
    executable = shutil.which("codex")
    if executable is None:
        raise RuntimeError("codex executable not found")
    return executable


def codex_version() -> str:
    result = subprocess.run(
        [_codex(), "--version"], check=True, capture_output=True, text=True
    )
    return result.stdout.strip()


def generate_json_schema(destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [_codex(), "app-server", "generate-json-schema", "--out", str(destination)],
        check=True,
    )


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _method_variants(schema: dict[str, Any]) -> dict[str, dict[str, Any]]:
    variants: dict[str, dict[str, Any]] = {}
    for variant in schema.get("oneOf", []):
        method = variant.get("properties", {}).get("method", {}).get("enum")
        if method:
            variants[method[0]] = variant
    return variants


def _manifest(version: str, files: dict[str, Path]) -> dict[str, Any]:
    return {
        "codex_version": version,
        "generator": "codex app-server generate-json-schema",
        "required_methods": list(REQUIRED_METHODS),
        "files": {name: _sha256(path) for name, path in files.items()},
    }


def write_contract() -> None:
    version = codex_version()
    with tempfile.TemporaryDirectory(prefix="stackchan-codex-contract-") as directory:
        generated = Path(directory)
        generate_json_schema(generated)
        CONTRACT_DIR.mkdir(parents=True, exist_ok=True)
        files: dict[str, Path] = {}
        for name in SCHEMA_FILES:
            source = generated / name
            if not source.is_file():
                raise RuntimeError(f"generator did not produce {name}")
            target = CONTRACT_DIR / name
            target.write_bytes(source.read_bytes())
            files[name] = target
        (CONTRACT_DIR / MANIFEST_FILE).write_text(
            json.dumps(_manifest(version, files), indent=2) + "\n", encoding="utf-8"
        )
    print(f"PASS generated Codex {version} contract in {CONTRACT_DIR.relative_to(ROOT)}")


def check_contract() -> None:
    manifest_path = CONTRACT_DIR / MANIFEST_FILE
    if not manifest_path.is_file():
        raise RuntimeError(f"missing {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    current_version = codex_version()
    if manifest.get("codex_version") != current_version:
        raise RuntimeError(
            f"version mismatch: contract={manifest.get('codex_version')!r}, "
            f"installed={current_version!r}; run --generate"
        )
    with tempfile.TemporaryDirectory(prefix="stackchan-codex-contract-check-") as directory:
        generated = Path(directory)
        generate_json_schema(generated)
        for name in SCHEMA_FILES:
            checked_in = CONTRACT_DIR / name
            candidate = generated / name
            if not checked_in.is_file() or checked_in.read_bytes() != candidate.read_bytes():
                raise RuntimeError(f"generated schema differs: {name}; run --generate")
    files = {name: CONTRACT_DIR / name for name in SCHEMA_FILES}
    expected = _manifest(current_version, files)
    if manifest != expected:
        raise RuntimeError("manifest hashes or method binding are stale; run --generate")
    print(f"PASS checked Codex {current_version} generated schemas and manifest")


def request(method: str, params: dict[str, Any], request_id: int = 1) -> dict[str, Any]:
    return {"id": request_id, "method": method, "params": params}


def validate_request(schema: dict[str, Any], payload: dict[str, Any]) -> None:
    variants = _method_variants(schema)
    method = payload.get("method")
    if method not in variants:
        raise AssertionError(f"method is not in generated ClientRequest schema: {method}")
    variant = variants[method]
    missing = set(variant.get("required", [])) - payload.keys()
    if missing:
        raise AssertionError(f"{method}: missing request fields {sorted(missing)}")
    params_ref = variant.get("properties", {}).get("params", {}).get("$ref")
    if not params_ref:
        return
    definition = schema["definitions"][params_ref.rsplit("/", 1)[-1]]
    required = set(definition.get("required", []))
    missing_params = required - payload["params"].keys()
    if missing_params:
        raise AssertionError(f"{method}: missing params {sorted(missing_params)}")


def run_offline_contract_tests() -> None:
    schema = json.loads((CONTRACT_DIR / "ClientRequest.json").read_text(encoding="utf-8"))
    variants = _method_variants(schema)
    missing = sorted(set(REQUIRED_METHODS) - variants.keys())
    if missing:
        raise AssertionError(f"required methods missing from generated schema: {missing}")
    samples = (
        request("initialize", {"clientInfo": {"name": "stackchan-contract", "version": "0"}}),
        request("thread/start", {"cwd": str(ROOT), "ephemeral": True}),
        request("turn/start", {"threadId": "offline-thread", "input": []}),
        request("turn/interrupt", {"threadId": "offline-thread", "turnId": "offline-turn"}),
    )
    for payload in samples:
        validate_request(schema, payload)
    print("PASS offline initialize/thread/start/turn/interrupt method contracts")
    print("PASS no credentials required; no real agent turn started")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true", help="refresh checked-in schemas")
    parser.add_argument("--check", action="store_true", help="compare schemas with local codex")
    parser.add_argument("--test", action="store_true", help="run offline method contracts")
    args = parser.parse_args()
    try:
        if args.generate:
            write_contract()
        if args.check:
            check_contract()
        if args.test or not (args.generate or args.check):
            run_offline_contract_tests()
        return 0
    except (AssertionError, OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"FAIL {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
